# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKrBolLRl3D3BpVE6RLsePPizGi9cAae
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("att_0_1778303821_c3a907.csv", low_memory=False)

print(df.head())
print(df.columns)
print(df.shape)

matches = df[['match_id', 'season', 'toss_winner', 'winner']].drop_duplicates()

print(matches.head())

# Toss winner also won match
toss_and_match_win = matches[matches['toss_winner'] == matches['winner']]

# Toss winner lost match
toss_but_lost = matches[matches['toss_winner'] != matches['winner']]

# Percentages
toss_win_rate = (len(toss_and_match_win) / len(matches)) * 100
toss_lose_rate = (len(toss_but_lost) / len(matches)) * 100

print("Toss Winner Won Match %:", toss_win_rate)
print("Toss Loser Won Match %:", toss_lose_rate)

labels = ['Toss Winner Won', 'Toss Loser Won']
values = [toss_win_rate, toss_lose_rate]

plt.figure(figsize=(6,5))
plt.bar(labels, values)

plt.ylabel('Win Percentage')
plt.title('Impact of Toss on Match Result')

plt.show()

def phase(over):
    if over <= 5:
        return 'Powerplay'
    elif over <= 14:
        return 'Middle Overs'
    else:
        return 'Death Overs'

df['phase'] = df['over'].apply(phase)

match_df = (
    df[["match_id", "season", "toss_winner", "toss_decision", "winner", "team1", "team2"]]
    .drop_duplicates("match_id")
    .copy()
)

def get_phase(over):
    if over < 6:  return "Powerplay (0–5)"
    if over < 15: return "Middle (6–14)"
    return "Death (15–19)"

df["phase"] = df["over"].apply(get_phase)

winner_map = match_df.set_index("match_id")["winner"].to_dict()
df["match_winner"] = df["match_id"].map(winner_map)
df["batting_won"]  = df["batting_team"] == df["match_winner"]

phase_runs = (
    df.groupby(["match_id", "innings", "phase", "batting_won"])["runs_total"]
    .sum()
    .reset_index()
)
phase_avg = (
    phase_runs.groupby(["phase", "batting_won"])["runs_total"]
    .mean()
    .round(1)
    .reset_index()
)
phase_avg["label"] = phase_avg["batting_won"].map({True: "Winners", False: "Losers"})
print("\nQ2 — Average runs per phase:")
print(phase_avg[["phase", "label", "runs_total"]].sort_values(["phase", "label"]).to_string(index=False))

print(df.columns.tolist())

df['result'] = df.apply(
    lambda x: 'Winning Team'
    if x['batting_team'] == x['winner']
    else 'Losing Team',
    axis=1
)

# Total runs scored in each phase per match
phase_totals = (
    df.groupby(
        ['match_id', 'batting_team', 'phase', 'result']
    )['runs_total']
    .sum()
    .reset_index()
)

# Average phase runs
phase_avg = (
    phase_totals.groupby(['phase', 'result'])['runs_total']
    .mean()
    .unstack()
)

print(phase_avg)

# Plot
phase_avg.plot(kind='bar', figsize=(8,5))

plt.title('Average Runs Per Phase')
plt.ylabel('Average Runs')

plt.xticks(rotation=0)

plt.show()

# =========================================
# TABLE 1
# Top 5 Batters by Runs
# =========================================

top_batters = (
    df.groupby('batter')['runs_batter']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)

top_batters.columns = ['Batter', 'Total Runs']

print("\nTop 5 Batters by Runs")
print(top_batters)



# =========================================
# TABLE 2
# Top 5 Bowlers by Wickets
# =========================================

# Exclude non-bowler wickets
valid_wickets = df[
    (df['wicket_player_out'].notna()) &
    (df['wicket_kind'] != 'run out')
]

top_bowlers = (
    valid_wickets.groupby('bowler')['wicket_player_out']
    .count()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)

top_bowlers.columns = ['Bowler', 'Total Wickets']

print("\nTop 5 Bowlers by Wickets")
print(top_bowlers)